services:
  - type: web
    name: rainfall-prediction-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    plan: free
    envVarsFromGroup: rainfall-prediction-api


